---
- name: Ansible Playbook
  hosts: webservers
  become: True
  #gather_facts: false
  #strategy: free
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: "/home/vagrant/ansible_test_dir"
        state: directory
        mode: 0755
        owner: vagrant
        group: vagrant

    - name: Generate 100 test files
      file:
        path: "/home/vagrant/ansible_test_dir/sample_file_{{ item }}.txt"
        state: touch
        mode: 0664
        owner: vagrant
        group: vagrant
      with_sequence: start=1 end=100

    - name: Find all created files and mark them for deletion
      find:
        paths: "/home/vagrant/ansible_test_dir"
        patterns: sample_file_*
      register: files_to_delete

    - name: Delete marked files
      file:
        path: "/home/vagrant/ansible_test_dir"
        state: absent
      with_items: "{{ files_to_delete.files }}"

    - name: Delete working directory
      file:
        path: "/home/vagrant/ansible_test_dir"
        state: absent
