---
- name: Reload initd
  command: initctl reload-configuration

- name: Restart Kafka service
  service:
    name: kafka
    state: restarted
  when: kafka_restart

- name: Restart Kafka systemd
  service:
    name: kafka
    state: restarted
    daemon_reload: true
  when: kafka_restart
